### ISSUE TITLE
Query buffers with drm prime file descriptors

### ISSUE THREAD

**Issue by FallingSnow** [Gnurou/v4l2r#5]
Correct me if I'm wrong but don't you need to query the buffers with file descriptors (specifically per plane) when "allocating" dma buffers? See https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/videodev2.h#L976

How would you pass those file descriptors to this function?
https://github.com/Gnurou/v4l2r/blob/a3976c239fb371bd6c03bb9cbd849fd5a426854a/lib/src/ioctl/querybuf.rs#L72

**Comment by FallingSnow** [comment]
Never mind, found the answer to my question
https://github.com/Gnurou/v4l2r/blob/686feabf771543e51f4636af79ae757e7149bda3/lib/examples/fwht_decoder/main.rs#L149

**Comment by Gnurou** [comment]
No worries! Actually surprised to see someone looking at this crate. ^_^;
