### ISSUE TITLE
Could be published to crates.io ?

### ISSUE THREAD

**Issue by lu-zero** [Gnurou/v4l2r#9]
It seems already in a fairly advanced state.

**Comment by Gnurou** [comment]
Yeah, I've been thinking about publishing it but a bit worried that this is very specific at the moment. The crate is not super useful unless you want to use a V4L2 stateful decoder or encoder, although the basis is there to build other use-cases. But if it could be convenient to you or someone else then maybe I should just do it?

**Comment by mfreeborn** [comment]
This is a great API, please consider publishing to crates.io!

**Comment by Gnurou** [comment]
This will need me to review the code and update the API a bit as I was not very versed in Rust when I started it, but I will try to get to it in the next few weeks.

**Comment by lu-zero** [comment]
May I help you? :)

**Comment by Gnurou** [comment]
Probably! :) The main problem I believe is that I am not very comfortable putting it on crates.io in the current state - I need the API to be more consistent, and the documentation to be more useful. So I know it's vague but if you have experience in that domain and want to submit a few PRs, I'd be happy to discuss!

**Comment by Gnurou** [comment]
Closing as we have published versions (albeit not a stable API yet) on crates.io.

**Comment by lu-zero** [comment]
that reminds me I hadn't had time to review the API ...

**Comment by Gnurou** [comment]
Would appreciate. Please be severe. :)
